### ISSUE TITLE
Redundant matvec calls

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/numopt#21]
https://github.com/GQCG/numopt/blob/3a0345f4ba70bcf0d5dba35917dcbed8cd9a89aa/src/DavidsonSolver.cpp#L107

https://github.com/GQCG/numopt/blob/3a0345f4ba70bcf0d5dba35917dcbed8cd9a89aa/src/DavidsonSolver.cpp#L199
Possibility for:
replacing multiple matvecs in for loops with sinlge a matvec on multiple vectors at once (matrix of few column vectors)

**Comment by lelemmen** [comment]
Thanks to Eigen's templatization, this wouldn't require an API change.
